# -*- coding: utf-8 -*-


# 45)
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle    T(n) = n(n+1)/2   =>  1, 3, 6, 10, 15, ...
# Pentagonal  P(n) = n(3n−1)/2  =>  1, 5, 12, 22, 35, ...
# Hexagonal   H(n) = n(2n−1)    =>  1, 6, 15, 28, 45, ...
#
# It can be verified that T(285) = P(165) = H(143) = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

# --------------------------------------------------------------------------------------
# Note that all hexagonal numbers are triangular numbers (but the converse is not True)!
# --------------------------------------------------------------------------------------

hexagonal = lambda x: (x*(2*x-1))
pentagonal = lambda x: (x*(3*x-1))/2

penta = {pentagonal(x):1 for x in xrange(166, 50000)}

c = 286

while True:
    hexagon = hexagonal(c)
    c += 1
    if penta.get(hexagon, None) is not None:
        break

ans = hexagon
print ans  # 1533776805
